events {}

http {

    upstream frontend {
        server frontend-blue:3000;

        # To switch traffic:
        # Change frontend-blue → frontend-green
    }

    server {

        listen 80;

        location / {
            proxy_pass http://frontend;
        }
    }
}