pipeline {
    agent any

    stages {

        stage('Checkout') {
            steps {
                checkout scm
            }
        }

        stage('Build Containers') {
            steps {
                sh 'docker-compose -f docker/docker-compose.green.yml up -d --build'
            }
        }

        stage('Health Check') {
            steps {
                sh 'docker ps'
            }
        }
    }
}